modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "testmod"
version = "${version}"
displayName = "TestMod"
authors = "Bartek Kansy"
description = '''
Test mod for Prism API
'''
#logoFile = ""

[[dependencies.testmod]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"
